repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.8
      entry: black
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: python -m pytest ./
      language: system
      types: [python]
      stages: [commit]
