repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.8
      entry: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      language_version: python3.8
      entry: flake8
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: pytest
      language: system
      types: [python]
      stages: [commit]
